version: '3.9'
services:
  make-recall-decision-api:
    build:
      context: .
    networks:
      - hmpps
    container_name: make-recall-decision-api
    ports:
      - "8080:8080"
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health/ping"]
    environment:
      - SERVER_PORT=8080
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth # auth comes from UI docker-compose
      - OFFENDER_SEARCH_ENDPOINT_URL=http://fake-offender-search-api:8080
      - COMMUNITY_API_ENDPOINT_URL=http://fake-community-api:8080
      - ARN_API_ENDPOINT_URL=http://fake-arn-api:8080
      - GOTENBERG_ENDPOINT_URL=http://gotenberg:3000
      - SYSTEM_CLIENT_ID=make-recall-decision-api
      - SYSTEM_CLIENT_SECRET=clientsecret
      - POSTGRES_HOST=postgres:5432
      - POSTGRES_DBNAME=make_recall_decision
      - POSTGRES_USERNAME=mrd_user
      - POSTGRES_PASSWORD=secret

  gotenberg:
    image: gotenberg/gotenberg:7.6.0
    networks:
      - hmpps
    container_name: gotenberg
    ports:
      - "9091:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
    environment:
      - LOG_LEVEL=DEBUG

  postgres:
    image: postgres:14-alpine
    networks:
      - hmpps
    container_name: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=mrd_user
      - POSTGRES_DB=make_recall_decision

  fake-offender-search-api:
    image: wiremock/wiremock
    networks:
      - hmpps
    container_name: fake-offender-search-api
    ports:
      - "9080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ping" ]
    command: --verbose --local-response-templating
    volumes:
      - ./fake-offender-search-api:/home/wiremock

  fake-community-api:
    image: wiremock/wiremock
    networks:
      - hmpps
    container_name: fake-community-api
    ports:
      - "9081:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/ping" ]
    command: --verbose --local-response-templating
    volumes:
      - ./fake-community-api:/home/wiremock

  fake-arn-api:
    image: wiremock/wiremock
    networks:
      - hmpps
    container_name: fake-arn-api
    ports:
      - "9071:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/ping" ]
    command: --verbose --local-response-templating
    volumes:
      - ./fake-arn-api:/home/wiremock

  fake-cvl-api:
    image: wiremock/wiremock
    networks:
      - hmpps
    container_name: fake-cvl-api
    ports:
      - "9070:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/ping" ]
    command: --verbose --local-response-templating
    volumes:
      - ./fake-cvl-api:/home/wiremock

networks:
  hmpps:
    name: hmpps
