version: '3.9'
services:
  make-recall-decision-api:
    build:
      context: .
    networks:
      - hmpps
    container_name: make-recall-decision-api
    ports:
      - "8080:8080"
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth # auth comes from UI docker-compose
      - PROBATION_OFFENDER_SEARCH_ENDPOINT_URL=http://fake-probation-offender-search-api:8080
      - PROBATION_COMMUNITY_API_ENDPOINT_URL=http://fake-probation-community-api:8080
      - GOTENBERG_ENDPOINT_URL=http://gotenberg:3000
      - SYSTEM_CLIENT_ID=make-recall-decision-api
      - SYSTEM_CLIENT_SECRET=clientsecret
      - POSTGRES_HOST=postgres:5432
      - POSTGRES_DBNAME=make_recall_decision
      - POSTGRES_USERNAME=mrd_user
      - POSTGRES_PASSWORD=secret

  gotenberg:
    image: gotenberg/gotenberg:7.5.2
    networks:
      - hmpps
    container_name: gotenberg
    ports:
      - "9091:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
    environment:
      - LOG_LEVEL=DEBUG

  postgres:
    image: postgres:13-alpine
    networks:
      - hmpps
    container_name: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=mrd_user
      - POSTGRES_DB=make_recall_decision

  fake-probation-offender-search-api:
    build: ./fake-probation-offender-search-api
    networks:
      - hmpps
    container_name: fake-probation-offender-search-api
    ports:
      - "9080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ping" ]
    command: --verbose --local-response-templating

  fake-probation-community-api:
    build: ./fake-probation-community-api
    networks:
      - hmpps
    container_name: fake-probation-community-api
    ports:
      - "9081:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/ping" ]
    command: --verbose --local-response-templating

networks:
  hmpps:
    name: hmpps
