version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-mrd_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: make_recall_decision
      PGDATA: /data/postgres
    volumes:
      - "./src/main/resources/db/migration/V1_0__RECOMMENDATIONS_TABLE.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./src/main/resources/db/migration/V1_1__RECOMMENDATIONS_TABLE.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./src/main/resources/db/migration/V1_2__RECOMMENDATIONS_TABLE.sql:/docker-entrypoint-initdb.d/3.sql"
      - "./src/main/resources/db/migration/V1_11__RECOMMENDATION_STATUS_TABLE.sql:/docker-entrypoint-initdb.d/4.sql"
      - "./src/main/resources/db/migration/V1_13__RECOMMENDATION_STATUS_TABLE.sql:/docker-entrypoint-initdb.d/5.sql"
      - "./src/main/resources/db/migration/V1_14__RECOMMENDATION_HISTORY_TABLE.sql:/docker-entrypoint-initdb.d/6.sql"
      - "./src/main/resources/db/migration/V1_15__RECOMMENDATION_STATUS_TABLE.sql:/docker-entrypoint-initdb.d/7.sql"
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
