offender:
  search:
    endpoint:
      url: https://probation-offender-search-dev.hmpps.service.justice.gov.uk

delius:
  integration:
    endpoint:
      url: https://make-recall-decisions-and-delius-dev.hmpps.service.justice.gov.uk

arn:
  api:
    endpoint:
      url: https://assess-risks-and-needs-dev.hmpps.service.justice.gov.uk

cvl:
  api:
    endpoint:
      url: https://create-and-vary-a-licence-api-dev.hmpps.service.justice.gov.uk

document-management:
  api:
    endpoint:
      url: https://document-api-dev.hmpps.service.justice.gov.uk

ppud-automation:
  api:
    endpoint:
      url: https://hmpps-ppud-automation-api-dev.hmpps.service.justice.gov.uk

prison:
  api:
    endpoint:
      url: https://prisoner-search-dev.prison.service.justice.gov.uk

hmpps:
  auth:
    url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

mrd:
  url: https://make-recall-decision-api-dev.hmpps.service.justice.gov.uk
  api:
    url: https://make-recall-decision-api-dev.hmpps.service.justice.gov.uk

document-template:
  # Any setting not specified or occurring only in the future will default to the 'default' template name
  part-a-template-settings[0].start-date-time: "2025-09-01T23:00Z" #2025-09-02T00:00Z in BST
  part-a-template-settings[0].template-name: "2025-09-02 - FTR48 Phase 1"
  part-a-template-settings[1].start-date-time: "2025-10-01T23:00Z" #2025-09-02T00:00Z in BST
  part-a-template-settings[1].template-name: "2026-11-01 - Risk to self"
