info.app:
  name: Make Recall Decision Api
  version: 1.0
  description: API to allow decisions about recalls to be made
  contact:
    name: HMPPS Digital Studio
    email: feedback@digital.justice.gov.uk

spring:
  flyway:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: make-recall-decision-api
  codec:
    max-in-memory-size: 30MB
  security:
    oauth2:
      client:
        registration:
          make-recall-decision-api:
            provider: hmpps-auth
            client-id: ${system.client.id:make-recall-decision-api}
            client-secret: ${system.client.secret:clientsecret}
            authorization-grant-type: client_credentials
            scope: read
          offender-search-api:
            provider: hmpps-auth
            client-id: ${system.client.id:make-recall-decision-api}
            client-secret: ${system.client.secret:clientsecret}
            authorization-grant-type: client_credentials
          arn-api:
            provider: hmpps-auth
            client-id: ${system.client.id:make-recall-decision-api}
            client-secret: ${system.client.secret:clientsecret}
            authorization-grant-type: client_credentials
          cvl-api:
            provider: hmpps-auth
            client-id: ${system.client.id:make-recall-decision-api}
            client-secret: ${system.client.secret:clientsecret}
            authorization-grant-type: client_credentials
          document-management-api:
            provider: hmpps-auth
            client-id: ${system.client.id:make-recall-decision-api}
            client-secret: ${system.client.secret:clientsecret}
            authorization-grant-type: client_credentials
          delius:
            provider: hmpps-auth
            client-id: ${system.client.id:make-recall-decision-api}
            client-secret: ${system.client.secret:clientsecret}
            authorization-grant-type: client_credentials
          ppud-automation-api:
            provider: hmpps-auth
            client-id: ${system.client.id:make-recall-decision-api}
            client-secret: ${system.client.secret:clientsecret}
            authorization-grant-type: client_credentials
          prison-api:
            provider: hmpps-auth
            client-id: ${system.client.id:make-recall-decision-api}
            client-secret: ${system.client.secret:clientsecret}
            authorization-grant-type: client_credentials

        provider:
          hmpps-auth:
            token-uri: ${hmpps.auth.url}/oauth/token
      resourceserver:
        jwt:
          jwk-set-uri: ${hmpps.auth.url}/.well-known/jwks.json

  jackson:
    parser:
      allow-backslash-escaping-any-character: true
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  datasource:
    url: jdbc:postgresql://${postgres.host:localhost:5432}/${postgres.dbname:make_recall_decision}
    username: ${postgres.username:mrd_user}
    password: ${postgres.password:secret}
    driver-class-name: org.postgresql.Driver

  profiles:
    group:
      test:
        - "stdout"

server:
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: native
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
      internal-proxies: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}|0:0:0:0:0:0:0:1|::1|100\.6[4-9]\.\d{1,3}\.\d{1,3}|100\.[7-9][0-9]{1}\.\d{1,3}\.\d{1,3}|100\.1[0-1][0-9]{1}\.\d{1,3}\.\d{1,3}|100\.12[0-7]\.\d{1,3}\.\d{1,3}
  shutdown: graceful
  error:
    include-message: always

housekeeping:
  sendDomainEvents: false

management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: 'info, health, prometheus'
  endpoint:
    health:
      enabled: true
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
      probes:
        enabled: true
    info:
      enabled: true
      cache:
        time-to-live: 2000ms
    prometheus:
      enabled: true

hmpps:
  auth:
    url: http://localhost:9090/auth
  sar:
    additionalAccessRole: MAKE_RECALL_DECISION

offender:
  search:
    endpoint:
      url: http://localhost:9080

delius:
  integration:
    endpoint:
      url: http://localhost:9082

arn:
  api:
    endpoint:
      url: http://localhost:9071

document-management:
  client:
    timeout: 10
  api:
    endpoint:
      url: http://localhost:9072

cvl:
  client:
    timeout: 20
  api:
    endpoint:
      url: http://localhost:9070

gotenberg:
  endpoint:
    url: http://localhost:9091

ndelius:
  client:
    timeout: 10

oasys:
  arn:
    client:
      timeout: 15

ppud-automation:
  client:
    timeout: 120
  api:
    endpoint:
      url: http://localhost:9370

prison:
  client:
    timeout: 30
  api:
    endpoint:
      url: http://localhost:9270

---
mrd:
  url: ${mrd.url}
  api:
    url: ${mrd.api.url}

cloud:
  aws:
    stack:
      auto: false
    region:
      static: eu-west-2
aws:
  provider: aws
  region: eu-west-2

hmpps.sqs:
  topics:
    hmpps-domain-events:
      arn: ${hmpps.domain.event.topic.arn}
      accessKeyId: ${hmpps.domain.event.topic.access.key.id}
      secretAccessKey: ${hmpps.domain.event.topic.secret.access.key}
      asyncClient: true

spring:
  config:
    activate:
      on-profile: default
---
