offender:
  search:
    endpoint:
      url: https://probation-offender-search-dev.hmpps.service.justice.gov.uk

community:
  endpoint:
    url: https://community-api-secure.test.delius.probation.hmpps.dsd.io

hmpps:
  auth:
    url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
