hmpps.auth.url: http://localhost:8090/auth

community:
  endpoint:
    url: http://localhost:8092

offender:
  search:
    endpoint:
      url: http://localhost:8093
#TODO is this availble on 8093 in dev?
