---
# Per environment values which override defaults in make-recall-decision-api/values.yaml

generic-service:
  ingress:
    host: make-recall-decision-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

generic-prometheus-alerts:
  alertSeverity: make-recall-decision-nonprod
