---
# Per environment values which override defaults in make-recall-decision-api/values.yaml

generic-service:
  ingress:
    host: make-recall-decision-api.hmpps.service.justice.gov.uk

  env:
    SENTRY_ENVIRONMENT: PROD
    HMPPS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    DELIUS_INTEGRATION_ENDPOINT_URL: https://make-recall-decisions-and-delius.hmpps.service.justice.gov.uk
    ARN_API_ENDPOINT_URL: https://assess-risks-and-needs.hmpps.service.justice.gov.uk
    DOCUMENT_MANAGEMENT_API_ENDPOINT_URL: https://document-api.hmpps.service.justice.gov.uk
    CVL_API_ENDPOINT_URL: https://create-and-vary-a-licence-api.hmpps.service.justice.gov.uk
    PPUD_AUTOMATION_API_ENDPOINT_URL: https://hmpps-ppud-automation-api.hmpps.service.justice.gov.uk
    PRISON_API_ENDPOINT_URL: https://prison-api.prison.service.justice.gov.uk
    MRD_URL: https://make-recall-decision.hmpps.service.justice.gov.uk
    MRD_API_URL: https://make-recall-decision-api.hmpps.service.justice.gov.uk
    HOUSEKEEPING_SENDDOMAINEVENTS: true
    # we cannot override a single item in a list - the whole list is replaced, so we define the whole thing again
    DOCUMENTTEMPLATE_PARTATEMPLATESETTINGS_0_STARTDATETIME: "2025-09-01T23:00Z" # 2025-09-02T00:00Z in BST, bring forward dev for testing
    DOCUMENTTEMPLATE_PARTATEMPLATESETTINGS_0_TEMPLATENAME: "2025-09-02 - FTR48 Phase 1"

  postgresDatabaseRestore:
    enabled: true
    timeout: 10800
    schedule: "30 7 * * 1-5"

    namespace_secrets:
      make-recall-decision-api-database:
        DB_NAME: "name"
        DB_USER: "username"
        DB_PASS: "password"
        DB_HOST: "host"
      make-recall-decision-api-database-output-preprod:
        DB_NAME_PREPROD: "name"
        DB_USER_PREPROD: "username"
        DB_PASS_PREPROD: "password"
        DB_HOST_PREPROD: "host"
    env:
      FORCE_RUN: true

generic-prometheus-alerts:
  alertSeverity: make-recall-decision-prod
  # Requires 15 health 500s in 5 minutes
  ingress5xxHealthEndpointThreshold: 0.05

gotenberg:
  alertSeverity: make-recall-decision-prod

