---
# Per environment values which override defaults in make-recall-decision-api/values.yaml

generic-service:
  ingress:
    host: make-recall-decision-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    SENTRY_ENVIRONMENT: PRE-PROD
    HMPPS_AUTH_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    OFFENDER_SEARCH_ENDPOINT_URL: https://probation-offender-search-preprod.hmpps.service.justice.gov.uk
    COMMUNITY_API_ENDPOINT_URL: https://community-api-secure.pre-prod.delius.probation.hmpps.dsd.io
    ARN_API_ENDPOINT_URL: https://assess-risks-and-needs-preprod.hmpps.service.justice.gov.uk
    CVL_API_ENDPOINT_URL: https://create-and-vary-a-licence-api-preprod.hmpps.service.justice.gov.uk

generic-prometheus-alerts:
  alertSeverity: make-recall-decision-nonprod

gotenberg:
  alertSeverity: make-recall-decision-nonprod
