---
# Per environment values which override defaults in make-recall-decision-api/values.yaml

generic-service:
  ingress:
    host: make-recall-decision-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    SENTRY_ENVIRONMENT: PRE-PROD
    HMPPS_AUTH_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    PROBATION_OFFENDER_SEARCH_ENDPOINT_URL: https://probation-offender-search-preprod.hmpps.service.justice.gov.uk
    COMMUNITY_API_ENDPOINT: https://community-api-secure.pre-prod.delius.probation.hmpps.dsd.io

generic-prometheus-alerts:
  alertSeverity: make-recall-decision-nonprod
