---
# Per environment values which override defaults in make-recall-decision-api/values.yaml

generic-service:
  ingress:
    host: make-recall-decision-api.hmpps.service.justice.gov.uk

  env:
    SENTRY_ENVIRONMENT: PROD
    HMPPS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    PROBATION_OFFENDER_SEARCH_ENDPOINT_URL: https://probation-offender-search.hmpps.service.justice.gov.uk
    COMMUNITY_API_ENDPOINT: https://community-api-public.test.probation.service.justice.gov.uk

generic-prometheus-alerts:
  alertSeverity: make-recall-decision-prod
