---
# Per environment values which override defaults in make-recall-decision-api/values.yaml

generic-service:
  ingress:
    host: make-recall-decision-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    SENTRY_ENVIRONMENT: PRE-PROD
    HMPPS_AUTH_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    DELIUS_INTEGRATION_ENDPOINT_URL: https://make-recall-decisions-and-delius-preprod.hmpps.service.justice.gov.uk
    ARN_API_ENDPOINT_URL: https://assess-risks-and-needs-preprod.hmpps.service.justice.gov.uk
    CVL_API_ENDPOINT_URL: https://create-and-vary-a-licence-api-preprod.hmpps.service.justice.gov.uk
    DOCUMENT_MANAGEMENT_API_ENDPOINT_URL: https://document-api-preprod.hmpps.service.justice.gov.uk
    PPUD_AUTOMATION_API_ENDPOINT_URL: https://hmpps-ppud-automation-api-preprod.hmpps.service.justice.gov.uk
    PRISON_API_ENDPOINT_URL: https://prison-api-preprod.prison.service.justice.gov.uk
    MRD_URL: https://make-recall-decision-preprod.hmpps.service.justice.gov.uk
    MRD_API_URL: https://make-recall-decision-api-preprod.hmpps.service.justice.gov.uk
    HOUSEKEEPING_SENDDOMAINEVENTS: true
    # we cannot override a single item in a list - the whole list is replaced, so we define the whole thing again
    DOCUMENTTEMPLATE_PARTATEMPLATESETTINGS_0_STARTDATETIME: "2025-07-30T23:45Z"
    DOCUMENTTEMPLATE_PARTATEMPLATESETTINGS_0_TEMPLATENAME: "NAT Recall Part A London Template - obtained 231114 - v2025-07-29.docx"
    DOCUMENTTEMPLATE_PARTAPREVIEWTEMPLATESETTINGS_0_STARTDATETIME: "2025-07-30T23:45Z"
    DOCUMENTTEMPLATE_PARTAPREVIEWTEMPLATESETTINGS_0_TEMPLATENAME: "Preview NAT Recall Part A London Template - obtained 231114 - v2025-07-29"

  scheduledDowntime:
    enabled: true

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: make-recall-decision-nonprod

gotenberg:
  alertSeverity: make-recall-decision-nonprod
