---
# Per environment values which override defaults in make-recall-decision-api/values.yaml

generic-service:
  ingress:
    host: make-recall-decision-api.hmpps.service.justice.gov.uk

  env:
    SENTRY_ENVIRONMENT: PROD
    HMPPS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    OFFENDER_SEARCH_ENDPOINT_URL: https://probation-offender-search.hmpps.service.justice.gov.uk
    COMMUNITY_API_ENDPOINT_URL: https://community-api-secure.probation.service.justice.gov.uk
    ARN_API_ENDPOINT_URL: https://assess-risks-and-needs.hmpps.service.justice.gov.uk
    CVL_API_ENDPOINT_URL: https://create-and-vary-a-licence-api.hmpps.service.justice.gov.uk

generic-prometheus-alerts:
  alertSeverity: make-recall-decision-prod

gotenberg:
  alertSeverity: make-recall-decision-prod
