---
# Per environment values which override defaults in make-recall-decision-api/values.yaml

generic-service:
  ingress:
    host: make-recall-decision-api.hmpps.service.justice.gov.uk

generic-prometheus-alerts:
  alertSeverity: make-recall-decision-prod
