apiVersion: v2
appVersion: '1.0'
description: A Helm chart for Kubernetes
name: make-recall-decision-api
version: 0.2.0
dependencies:
  - name: gotenberg
    version: 0.1.0
    repository: file://subcharts/gotenberg
  - name: generic-service
    version: "2.8"
    repository: https://ministryofjustice.github.io/hmpps-helm-charts
  - name: generic-prometheus-alerts
    version: 1.3
    repository: https://ministryofjustice.github.io/hmpps-helm-charts
